"""
LiteVAE-style implementation for Fashion-MNIST reconstruction & denoising.

This code is GENERATED BY AN AI ASSISTANT for AI Assignment #1 (CISC3024
Pattern Recognition). It implements the core idea of LiteVAE
(Sadat et al., NeurIPS 2024): a variational autoencoder whose encoder is
front-loaded with a 2D Haar Discrete Wavelet Transform (DWT), plus a
lightweight feature-extraction / aggregation network and a fully
convolutional decoder.

Adaptation note:
  - The original LiteVAE uses 3 DWT levels (8x downsampling) on large images.
    Fashion-MNIST is 28x28, which supports exactly 2 DWT levels
    (28 -> 14 -> 7). We therefore use num_levels=2 (4x downsampling, latent
    grid 7x7) to stay integer-sized.
  - Only the light variant is used so the model trains fast on CPU.
"""

import os
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ----------------------------------------------------------------------
# 2D Haar discrete wavelet transform (DWT) and its inverse (IDWT)
# Implemented directly with tensor slicing (orthonormal Haar basis).
# ----------------------------------------------------------------------
def haar_dwt2d(x):
    """Forward 2-level-agnostic single-scale 2D Haar DWT.
    x: [B, C, H, W] with even H, W -> returns 4 subbands [B, C, H/2, W/2]."""
    x00 = x[:, :, 0::2, 0::2]
    x01 = x[:, :, 0::2, 1::2]
    x10 = x[:, :, 1::2, 0::2]
    x11 = x[:, :, 1::2, 1::2]
    ll = (x00 + x01 + x10 + x11) / 2.0
    lh = (x00 - x01 + x10 - x11) / 2.0   # horizontal detail
    hl = (x00 + x01 - x10 - x11) / 2.0   # vertical detail
    hh = (x00 - x01 - x10 + x11) / 2.0   # diagonal detail
    return ll, lh, hl, hh


def haar_idwt2d(ll, lh, hl, hh):
    """Inverse single-scale 2D Haar DWT."""
    x00 = (ll + lh + hl + hh) / 2.0
    x01 = (ll - lh + hl - hh) / 2.0
    x10 = (ll + lh - hl - hh) / 2.0
    x11 = (ll - lh - hl + hh) / 2.0
    b, c, h, w = x00.shape
    out = x00.new_empty(b, c, h * 2, w * 2)
    out[:, :, 0::2, 0::2] = x00
    out[:, :, 0::2, 1::2] = x01
    out[:, :, 1::2, 0::2] = x10
    out[:, :, 1::2, 1::2] = x11
    return out


# ----------------------------------------------------------------------
# Encoder: DWT front-end -> per-band feature extraction -> aggregation
# ----------------------------------------------------------------------
class DWTEncoder(nn.Module):
    """VAE encoder that first decomposes the image with DWT.

    For 28x28 input with num_levels=2:
      level1 bands: 14x14 (lh1, hl1, hh1 -> 3 channels)
      level2 bands: 7x7   (ll2, lh2, hl2, hh2 -> 4 channels)
    """
    def __init__(self, in_channels=1, latent_dim=16, num_levels=2,
                 base_ch=32):
        super().__init__()
        self.num_levels = num_levels
        self.latent_dim = latent_dim

        # Feature extraction at finest band resolution (14x14)
        self.feat1 = nn.Sequential(
            nn.Conv2d(3 * in_channels, base_ch, 3, padding=1),
            nn.BatchNorm2d(base_ch), nn.GELU(),
            nn.Conv2d(base_ch, base_ch, 3, padding=1),
            nn.BatchNorm2d(base_ch), nn.GELU(),
        )
        # Feature extraction at coarsest band resolution (7x7)
        self.feat2 = nn.Sequential(
            nn.Conv2d(4 * in_channels, base_ch, 3, padding=1),
            nn.BatchNorm2d(base_ch), nn.GELU(),
            nn.Conv2d(base_ch, base_ch, 3, padding=1),
            nn.BatchNorm2d(base_ch), nn.GELU(),
        )
        # Aggregation
        self.agg = nn.Sequential(
            nn.Conv2d(2 * base_ch, base_ch, 3, padding=1), nn.GELU(),
            nn.Conv2d(base_ch, base_ch, 1), nn.GELU(),
        )
        self.to_latent = nn.Conv2d(base_ch, 2 * latent_dim, 1)  # mu + logvar

    def forward(self, x):
        # DWT front end
        ll1, lh1, hl1, hh1 = haar_dwt2d(x)              # 14x14
        ll2, lh2, hl2, hh2 = haar_dwt2d(ll1)            # 7x7

        # concatenate level-1 high-frequency bands
        b1 = torch.cat([lh1, hl1, hh1], dim=1)          # [B,3C,14,14]
        f1 = self.feat1(b1)                             # [B,base,14,14]
        f1 = F.avg_pool2d(f1, 2)                        # [B,base,7,7]

        # concatenate level-2 bands (low + high)
        b2 = torch.cat([ll2, lh2, hl2, hh2], dim=1)     # [B,4C,7,7]
        f2 = self.feat2(b2)                             # [B,base,7,7]

        agg = torch.cat([f1, f2], dim=1)                # [B,2base,7,7]
        h = self.agg(agg)                               # [B,base,7,7]
        params = self.to_latent(h)                      # [B,2*latent,7,7]
        mu, logvar = params[:, :self.latent_dim], params[:, self.latent_dim:]
        return mu, logvar


# ----------------------------------------------------------------------
# Decoder: purely convolutional transposed network
# ----------------------------------------------------------------------
class ConvDecoder(nn.Module):
    def __init__(self, latent_dim=16, base_ch=32):
        super().__init__()
        self.net = nn.Sequential(
            nn.ConvTranspose2d(latent_dim, base_ch * 2, 4, stride=2, padding=1),  # 7->14
            nn.BatchNorm2d(base_ch * 2), nn.GELU(),
            nn.ConvTranspose2d(base_ch * 2, base_ch, 4, stride=2, padding=1),     # 14->28
            nn.BatchNorm2d(base_ch), nn.GELU(),
            nn.Conv2d(base_ch, 1, 3, padding=1),
            nn.Sigmoid(),
        )

    def forward(self, z):
        # z: [B, latent_dim, 7, 7] spatial latent grid -> upsample to 28x28
        return self.net(z)


# ----------------------------------------------------------------------
# Full LiteVAE (VAE) module
# ----------------------------------------------------------------------
class LiteVAE(nn.Module):
    def __init__(self, in_channels=1, latent_dim=16):
        super().__init__()
        self.encoder = DWTEncoder(in_channels, latent_dim)
        self.decoder = ConvDecoder(latent_dim)
        self.latent_dim = latent_dim

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        mu, logvar = self.encoder(x)
        z = self.reparameterize(mu, logvar)  # [B, latent_dim, 7, 7]
        recon = self.decoder(z)
        return recon, mu, logvar


# ----------------------------------------------------------------------
# Losses: reconstruction (MSE) + KL divergence
# ----------------------------------------------------------------------
def vae_loss(recon, target, mu, logvar):
    recon_loss = F.mse_loss(recon, target, reduction="mean")
    kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()) / mu.shape[0]
    return recon_loss, kl


def kl_weight(epoch, max_epochs, warmup_frac=0.2, max_beta=1.0):
    """Linear anneal of KL weight to avoid posterior collapse early on.
    Kept for API compatibility; the KL scale in main() is set small by default
    (as in stable-diffusion / LiteVAE training where reconstruction dominates)."""
    warmup = max(1, int(max_epochs * warmup_frac))
    if epoch < warmup:
        return max_beta * (epoch + 1) / warmup
    return max_beta


# ----------------------------------------------------------------------
# Metrics
# ----------------------------------------------------------------------
def psnr(a, b, max_val=1.0):
    mse = torch.mean((a - b) ** 2).item()
    if mse == 0:
        return float("inf")
    return 10.0 * np.log10(max_val ** 2 / mse)


def _gaussian_kernel(ksize=11, sigma=1.5):
    ax = torch.linspace(-(ksize - 1) / 2, (ksize - 1) / 2, ksize)
    g = torch.exp(-(ax ** 2) / (2 * sigma ** 2))
    g = (g / g.sum()).view(1, 1, -1, 1)
    return g, g.transpose(2, 3)


def ssim(a, b, ksize=11, sigma=1.5):
    """Structural similarity (full-image, single channel)."""
    a = a.float()
    b = b.float()
    gx, gy = _gaussian_kernel(ksize, sigma)
    # img: [B,1,H,W]
    mu_a = F.conv2d(a.view(-1, 1, a.shape[-2], a.shape[-1]), gx, padding=ksize // 2)
    mu_a = F.conv2d(mu_a, gy, padding=ksize // 2)
    mu_b = F.conv2d(b.view(-1, 1, b.shape[-2], b.shape[-1]), gx, padding=ksize // 2)
    mu_b = F.conv2d(mu_b, gy, padding=ksize // 2)
    mu_a_sq, mu_b_sq, mu_ab = mu_a ** 2, mu_b ** 2, mu_a * mu_b
    var_a = F.conv2d(a.view(-1, 1, a.shape[-2], a.shape[-1]) ** 2, gx, padding=ksize // 2)
    var_a = F.conv2d(var_a, gy, padding=ksize // 2) - mu_a_sq
    var_b = F.conv2d(b.view(-1, 1, b.shape[-2], b.shape[-1]) ** 2, gx, padding=ksize // 2)
    var_b = F.conv2d(var_b, gy, padding=ksize // 2) - mu_b_sq
    cov = F.conv2d((a.view(-1, 1, a.shape[-2], a.shape[-1]) * b.view(-1, 1, b.shape[-2], b.shape[-1])),
                   gx, padding=ksize // 2)
    cov = F.conv2d(cov, gy, padding=ksize // 2) - mu_ab
    C1, C2 = 0.01 ** 2, 0.03 ** 2
    ssim_map = ((2 * mu_ab + C1) * (2 * cov + C2)) / ((mu_a_sq + mu_b_sq + C1) * (var_a + var_b + C2))
    return ssim_map.mean().item()


@torch.no_grad()
def evaluate(model, loader, device, noise_std):
    """Returns metrics for (a) clean reconstruction from clean input and
    (b) denoising (noisy input -> clean target)."""
    model.eval()
    totals = {key: [0.0, 0.0] for key in ("mse", "psnr", "ssim")}
    n = 0
    for x, _ in loader:
        x = x.to(device)
        noisy = (x + torch.randn_like(x) * noise_std).clamp(0, 1)
        recon_clean, _, _ = model(x)
        recon_denoise, _, _ = model(noisy)
        recon_clean = recon_clean.detach().clamp(0, 1)
        recon_denoise = recon_denoise.detach().clamp(0, 1)
        b = x.shape[0]
        n += b
        # clean reconstruction (input == target == x)
        totals["mse"][0] += torch.mean((recon_clean - x) ** 2).item() * b
        totals["psnr"][0] += psnr(recon_clean, x) * b
        totals["ssim"][0] += ssim(recon_clean, x) * b
        # denoising (input == noisy, target == x)
        totals["mse"][1] += torch.mean((recon_denoise - x) ** 2).item() * b
        totals["psnr"][1] += psnr(recon_denoise, x) * b
        totals["ssim"][1] += ssim(recon_denoise, x) * b
    out = {}
    for key, (c, d) in totals.items():
        out[(key, "clean")] = c / n
        out[(key, "denoise")] = d / n
    return out


# ----------------------------------------------------------------------
# Plotting
# ----------------------------------------------------------------------
@torch.no_grad()
def plot_samples(model, loader, device, noise_std, out_path, n=8):
    model.eval()
    x, _ = next(iter(loader))
    x = x[:n].to(device)
    noisy = (x + torch.randn_like(x) * noise_std).clamp(0, 1)
    recon, _, _ = model(noisy)
    recon = recon.detach().clamp(0, 1)
    fig, axes = plt.subplots(3, n, figsize=(2 * n, 6))
    titles = ["Original", "Noisy", "Reconstructed"]
    for r, row in enumerate(axes):
        imgs = [x, noisy, recon][r]
        for i, ax in enumerate(row):
            ax.imshow(imgs[i].cpu().squeeze(0), cmap="gray")
            ax.axis("off")
            if i == 0:
                ax.set_ylabel(titles[r], fontsize=11)
    plt.suptitle("LiteVAE: Fashion-MNIST denoising samples", fontsize=13)
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    plt.close(fig)


def plot_curves(history, out_path):
    fig, ax1 = plt.subplots(figsize=(6, 4))
    ax1.plot(history["recon"], label="Recon loss", color="tab:blue")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Reconstruction loss", color="tab:blue")
    ax1.tick_params(axis="y", labelcolor="tab:blue")
    ax2 = ax1.twinx()
    ax2.plot(history["kl"], label="KL loss", color="tab:red")
    ax2.set_ylabel("KL divergence", color="tab:red")
    ax2.tick_params(axis="y", labelcolor="tab:red")
    plt.title("LiteVAE training curves (Fashion-MNIST)")
    fig.tight_layout()
    fig.savefig(out_path, dpi=120)
    plt.close(fig)


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=15)
    ap.add_argument("--batch-size", type=int, default=128)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--latent-dim", type=int, default=16)
    ap.add_argument("--kl-weight", type=float, default=1e-4,
                    help="beta scaling of KL term (small so reconstruction dominates, "
                         "as in SD-VAE / LiteVAE training)")
    ap.add_argument("--noise-std", type=float, default=0.2)
    ap.add_argument("--data", type=str, default="./data")
    ap.add_argument("--out", type=str, default="./output/litevae_fmnist.png")
    ap.add_argument("--limit", type=int, default=-1, help="subsample trainset for quick runs")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    tf = transforms.Compose([transforms.ToTensor()])  # values in [0,1]
    train_ds = datasets.FashionMNIST(root=args.data, train=True, download=True, transform=tf)
    test_ds = datasets.FashionMNIST(root=args.data, train=False, download=True, transform=tf)
    if args.limit > 0:
        rng = torch.Generator().manual_seed(0)
        idx = torch.randperm(len(train_ds), generator=rng)[:args.limit]
        train_ds = torch.utils.data.Subset(train_ds, idx)
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=0)
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False)

    model = LiteVAE(latent_dim=args.latent_dim).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr)
    history = {"recon": [], "kl": []}

    for ep in range(1, args.epochs + 1):
        model.train()
        r_loss = k_loss = 0.0
        n = 0
        for x, _ in train_loader:
            x = x.to(device)
            noisy = (x + torch.randn_like(x) * args.noise_std).clamp(0, 1)
            recon, mu, logvar = model(noisy)
            recon_loss, kl = vae_loss(recon, x, mu, logvar)
            loss = recon_loss + args.kl_weight * kl
            opt.zero_grad()
            loss.backward()
            opt.step()
            r_loss += recon_loss.item() * x.shape[0]
            k_loss += kl.item() * x.shape[0]
            n += x.shape[0]
        history["recon"].append(r_loss / n)
        history["kl"].append(k_loss / n)
        ev = evaluate(model, test_loader, device, args.noise_std)
        print(f"Epoch {ep:2d}/{args.epochs} | recon={history['recon'][-1]:.5f} "
              f"kl={history['kl'][-1]:.2f} | clean MSE={ev[('mse','clean')]:.5f} "
              f"PSNR={ev[('psnr','clean')]:.2f} SSIM={ev[('ssim','clean')]:.4f} | "
              f"denoise PSNR={ev[('psnr','denoise')]:.2f}")

    # final metrics
    ev = evaluate(model, test_loader, device, args.noise_std)
    print(f"\n=== FINAL TEST (noise std={args.noise_std}) ===")
    print(f"Clean reconstruction : MSE={ev[('mse','clean')]:.5f} "
          f"PSNR={ev[('psnr','clean')]:.2f} dB  SSIM={ev[('ssim','clean')]:.4f}")
    print(f"Denoising (std={args.noise_std}): MSE={ev[('mse','denoise')]:.5f} "
          f"PSNR={ev[('psnr','denoise')]:.2f} dB  SSIM={ev[('ssim','denoise')]:.4f}")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    base = os.path.splitext(args.out)[0]
    plot_samples(model, test_loader, device, args.noise_std, args.out)
    plot_curves(history, base + "_curves.png")
    torch.save(model.state_dict(), base + "_weights.pt")
    print("Saved figures & weights to", os.path.dirname(args.out))


if __name__ == "__main__":
    main()